# Use Python 3.9 as base image
FROM python:3.9-slim-buster

# Set working directory for the app
WORKDIR /app
COPY example/ /usr/local/example

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN apt-get update && pip install --upgrade pip && pip install -r requirements.txt
# Copy the code into the container
COPY . .

# Expose port 8000 for the FastAPI app
EXPOSE 443

# Set Environment Variables
ENV MODULE_NAME=bing_chat
ENV VARIABLE_NAME=APP

# Start the FastAPI app
CMD ["uvicorn", "bing_chat:APP", "--host", "0.0.0.0", "--port", "443"]
